spring:
  datasource:
    url: jdbc:postgresql://prod-host:5432/tht_db
    username: tht_user
    password: ${DB_PASSWORD}

logging:
  level:
    root: WARN
    com.fadlan.tht: INFO

server:
  error:
    include-stacktrace: never
